#:import Clipboard kivy.core.clipboard.Clipboard
<Command>
    size_hint_y: None
    pos_hint: {"right": .98}
    height: self.texture_size[1]
    padding: 12, 10
    theme_text_color: "Custom"
    text_color: 1, 1, 1, 1
    canvas.before:
        Color:
            rgb: rgba(52, 0, 234, 255)
        RoundedRectangle:
            size: self.width, self.height
            pos: self.pos
            radius: [23, 23, 0, 23]
    on_touch_down:
        app.message_click()
<Response>
    size_hint_y: None
    pos_hint: {"x": .02}
    #height: self.texture_size[1]
    padding: 12, 10
    canvas.before:
        Color:
            rgb: (1, 1, 1, 1)
        RoundedRectangle:
            size: self.width, self.height
            pos: self.pos
            radius: [23, 23, 23, 0]
    BoxLayout:
        orientation: 'vertical'
        padding: 0
        Label:
            text: root.fro
            font_size: 12
            color: (0, 0, 1, 1)
            halign: 'left'
            size_hint_x: .22
        MDLabel:
            text: root.text
            font_size: 12
            halign: "center"
MDScreen:
    name: "chat"
    kkk: kkk
    bot_name: bot_name
    chat_list: chat_list
    text_input: text_input

    MDFloatLayout:
        MDFloatLayout:
            md_bg_color: 245/255, 245/255, 245/255, 1
            size_hint_y: .11
            pos_hint: {"center_y": .95}
            MDIconButton:
                icon: "arrow-left"
                pos_hint: {"center_y": .5}
                user_font_size: "30sp"
                theme_text_color: "Custom"
                text_color: rgba(26, 24, 58, 255)
                on_release:
                    root.manager.transition.direction = "right"
                    root.manager.current = "home"
            MDIconButton:
                icon: "content-copy"
                pos_hint: {"center_x": .9, "center_y": .5}
                on_release:
                    Clipboard.copy(kkk.text)
                    app.show_qr_code(kkk.text)

            MDLabel:
                text: ""
                id: bot_name
                pos_hint: {"center_y": .5}
                halign: "center"
                font_name: "BPoppins"
                font_size: "25sp"
                theme_text_color: "Custom"
                text_color: 53/255, 56/255, 60/255, 1
            MDLabel:
                text: ""
                id: kkk
                pos_hint: {"center_y": .5}
                halign: "center"
                font_name: "BPoppins"
                font_size: "0sp"
                theme_text_color: "Custom"
                text_color: 53/255, 56/255, 60/255, 1
                opacity: 0




        ScrollView:
            size_hint_y: .77
            pos_hint: {"x": 0, "y": .116}
            do_scroll_x: False
            do_scroll_y: True
            BoxLayout:
                id: chat_list
                orientation: "vertical"
                size: (root.width, root.height)
                height: self.minimum_height
                size_hint: None, None
                pso_hint: {"top": 10}
                cols: 1
                spacing: 5
        MDFloatLayout:
            md_bg_color: 245/255, 245/255, 245/255, 1
            size_hint_y: .11
            MDFloatLayout:
                size_hint: .7, .60
                pos_hint: {"center_x": .45, "center_y": .5}
                canvas:
                    Color:
                        rgb: (238/255, 238/255, 238/255, 1)
                    RoundedRectangle:
                        size: self.size
                        pos: self.pos
                        radius: [23, 23, 23, 23]
                TextInput:
                    id: text_input
                    hint_text: "Type something..."
                    size_hint: 1, None
                    pos_hint: {"center_x": .5, "center_y": .5}
                    font_size: "12sp"
                    height: self.minimum_height
                    multiline: False
                    cursor_color: 1, 170/255, 23/255, 1
                    cursor_width: "2sp"
                    foreground_color: 1, 170/255, 23/255, 1
                    background_color: 0, 0, 0, 0
                    padding: 15
                    font_name: "BPoppins"
            MDIconButton:
                icon: "send"
                pos_hint: {"center_x": .91, "center_y": .5}
                user_font_size: "18sp"
                theme_text_color: "Custom"
                text_color: 0, 0, 0, 1
                #foreground_color: rgba(0, 0, 0, 1)
                #md_bg_color: rgba(52, 0, 231, 255)
                on_release:
                    app.send_message_aaa(text_input.text, kkk.text)
            MDIconButton:
                icon: "file-upload"
                pos_hint: {"center_x": .8, "center_y": .5}
                user_font_size: "18sp"
                theme_text_color: "Custom"
                text_color: 0, 0, 0, 1
                #md_bg_color: rgba(52, 0, 231, 255)
                on_release:
                    app.file_chooser(kkk.text)
