#: import get_color_from_hex kivy.utils.get_color_from_hex

MDScreen:
    name: "help"
    MDFloatLayout:
        md_bg_color: 1, 1, 1, 1


        MDBottomAppBar:
            title: 'Bottom navigation'
            md_bg_color: .2, .2, .2, 1
            specific_text_color: 1, 1, 1, 1

        MDBottomNavigation:
            panel_color: 1, 1, 1, 1

            MDBottomNavigationItem:
                name: "home"
                text: "Home"
                icon: "home"

                MDIconButton:
                    icon: "arrow-left"
                    pos_hint: {"center_y": .95}
                    user_font_size: "30sp"
                    theme_text_color: "Custom"
                    text_color: rgba(26, 24, 58, 255)
                    on_release:
                        root.manager.transition.direction = "right"
                        root.manager.current = "main"

                MDLabel:
                    id: welcome_name
                    text: "Welcome ProtDos"
                    font_name: "BPoppins"
                    font_size: "23sp"
                    pos_hint: {"center_y": .8}
                    halign: "center"
                    color: rgba(34, 34, 34, 255)
                Button:
                    text: "Start chatting"
                    size_hint: .66, .065
                    pos_hint: {"center_x": .5, "center_y": .65}
                    background_color: 0, 0, 0, 0
                    front_name: "BPoppins"
                    on_release:
                        root.manager.transition.direction = "left"
                        root.manager.current = "chat"
                    canvas.before:
                        Color:
                            rgb: rgba(52, 0, 231, 255)
                        RoundedRectangle:
                            size: self.size
                            pos: self.pos
                            radius: [5]
                Button:
                    text: "Create a Group"
                    size_hint: .66, .065
                    pos_hint: {"center_x": .5, "center_y": .55}
                    background_color: 0, 0, 0, 0
                    front_name: "BPoppins"
                    color: rgba(52, 0, 231, 255)
                    on_release:
                        root.manager.transition.direction = "left"
                        root.manager.current = "group"
                    canvas.before:
                        Color:
                            rgb: rgba(52, 0, 231, 255)
                        Line:
                            width: 1.2
                            rounded_rectangle: self.x, self.y, self.width, self.height, 5, 5, 5, 5, 100
                Button:
                    text: "Join a Group"
                    size_hint: .66, .065
                    pos_hint: {"center_x": .5, "center_y": .45}
                    background_color: 0, 0, 0, 0
                    front_name: "BPoppins"
                    color: rgba(52, 0, 231, 255)
                    on_release:
                        root.manager.transition.direction = "left"
                        root.manager.current = "group"
                    canvas.before:
                        Color:
                            rgb: rgba(52, 0, 231, 255)
                        Line:
                            width: 1.2
                            rounded_rectangle: self.x, self.y, self.width, self.height, 5, 5, 5, 5, 100
                Button:
                    text: "Settings"
                    size_hint: .66, .065
                    pos_hint: {"center_x": .5, "center_y": .35}
                    background_color: 0, 0, 0, 0
                    front_name: "BPoppins"
                    color: rgba(52, 0, 231, 255)
                    on_release:
                        root.manager.transition.direction = "left"
                        root.manager.current = "settings"
                    canvas.before:
                        Color:
                            rgb: rgba(52, 0, 231, 255)
                        Line:
                            width: 1.2
                            rounded_rectangle: self.x, self.y, self.width, self.height, 5, 5, 5, 5, 100
                Button:
                    text: "Personal"
                    size_hint: .66, .065
                    pos_hint: {"center_x": .5, "center_y": .25}
                    background_color: 0, 0, 0, 0
                    front_name: "BPoppins"
                    color: rgba(52, 0, 231, 255)
                    on_release:
                        root.manager.transition.direction = "left"
                        root.manager.current = "personal"
                    canvas.before:
                        Color:
                            rgb: rgba(52, 0, 231, 255)
                        Line:
                            width: 1.2
                            rounded_rectangle: self.x, self.y, self.width, self.height, 5, 5, 5, 5, 100

                MDIconButton:
                    icon: "logout"
                    pos_hint: {"center_x": .9, "center_y": .05}
                    on_release:
                        root.manager.transition.direction = "left"
                        root.manager.current = "main"


            MDBottomNavigationItem:
                name: "test"
                text: "Chats"
                icon: "chat"

                MDIconButton:
                    icon: "arrow-left"
                    pos_hint: {"center_y": .95}
                    user_font_size: "30sp"
                    theme_text_color: "Custom"
                    text_color: rgba(26, 24, 58, 255)
                    on_release:
                        root.manager.transition.direction = "right"
                        root.manager.current = "main"

                MDLabel:
                    text: "Chats"
                    font_name: "BPoppins"
                    font_size: "23sp"
                    pos_hint: {"center_y": .8}
                    halign: "center"
                    color: rgba(34, 34, 34, 255)
                Button:
                    text: "Start chatting"
                    size_hint: .66, .065
                    pos_hint: {"center_x": .5, "center_y": .65}
                    background_color: 0, 0, 0, 0
                    front_name: "BPoppins"
                    on_release:
                        root.manager.transition.direction = "left"
                        root.manager.current = "chat"
                    canvas.before:
                        Color:
                            rgb: rgba(52, 0, 231, 255)
                        RoundedRectangle:
                            size: self.size
                            pos: self.pos
                            radius: [5]
                Button:
                    text: "Create new chat"
                    size_hint: .66, .065
                    pos_hint: {"center_x": .5, "center_y": .55}
                    background_color: 0, 0, 0, 0
                    front_name: "BPoppins"
                    color: rgba(52, 0, 231, 255)
                    on_release:
                        root.manager.transition.direction = "left"
                        root.manager.current = "chat"
                    canvas.before:
                        Color:
                            rgb: rgba(52, 0, 231, 255)
                        Line:
                            width: 1.2
                            rounded_rectangle: self.x, self.y, self.width, self.height, 5, 5, 5, 5, 100

            MDBottomNavigationItem:
                name: "test2"
                text: "Settings"
                icon: "account-settings"

                MDIconButton:
                    icon: "arrow-left"
                    pos_hint: {"center_y": .95}
                    user_font_size: "30sp"
                    theme_text_color: "Custom"
                    text_color: rgba(26, 24, 58, 255)
                    on_release:
                        root.manager.transition.direction = "right"
                        root.manager.current = "main"


            MDBottomNavigationItem:
                name: "test3"
                text: "Help"
                icon: "help-circle"

                MDIconButton:
                    icon: "arrow-left"
                    pos_hint: {"center_y": .95}
                    user_font_size: "30sp"
                    theme_text_color: "Custom"
                    text_color: rgba(26, 24, 58, 255)
                    on_release:
                        root.manager.transition.direction = "right"
                        root.manager.current = "main"

                MDLabel:
                    text: "Help Center"
                    font_name: "BPoppins"
                    font_size: "23sp"
                    pos_hint: {"center_y": .8}
                    halign: "center"
                    color: rgba(34, 34, 34, 255)
                MDLabel:
                    text: "Help Center"
                    font_name: "BPoppins"
                    font_size: "23sp"
                    pos_hint: {"center_y": .8}
                    halign: "center"
                    color: rgba(34, 34, 34, 255)
                MDLabel:
                    text: "Error?"
                    font_name: "BPoppins"
                    font_size: "15sp"
                    pos_hint: {"center_y": .7}
                    halign: "center"
                    color: rgba(34, 34, 34, 255)
                MDLabel:
                    text: "Coming soon..."
                    font_name: "BPoppins"
                    font_size: "18sp"
                    pos_hint: {"center_x": .6, "center_y": .65}
                    color: rgba(135, 133, 193, 255)
                MDLabel:
                    text: "Feedback"
                    font_name: "BPoppins"
                    font_size: "23sp"
                    pos_hint: {"center_y": .6}
                    halign: "center"
                    color: rgba(34, 34, 34, 255)
                MDLabel:
                    text: "Bugs"
                    font_name: "BPoppins"
                    font_size: "23sp"
                    pos_hint: {"center_y": .5}
                    halign: "center"
                    color: rgba(34, 34, 34, 255)



