#: import get_color_from_hex kivy.utils.get_color_from_hex
#: import webbrowser webbrowser

#: import TwoLineListItem kivymd.uix.list.TwoLineListItem
#: import Window kivy.core.window.Window

MDScreen:
    name: "home"
    username_icon: username_icon
    password_icon: password_icon
    text_input2: text_input2
    text_input3: text_input3
    welcome_name: welcome_name

    MDFloatLayout:
        md_bg_color: 1, 1, 1, 1


        MDBottomAppBar:
            title: 'Bottom navigation'
            md_bg_color: .2, .2, .2, 1
            specific_text_color: 1, 1, 1, 1

        MDBottomNavigation:
            panel_color: 1, 1, 1, 1

            MDBottomNavigationItem:
                name: "home"
                text: "Home"
                icon: "home"

                MDLabel:
                    id: welcome_name
                    text: "Welcome"
                    font_name: "BPoppins"
                    font_size: "23sp"
                    pos_hint: {"center_y": .8}
                    halign: "center"
                    color: rgba(34, 34, 34, 255)
                Button:
                    text: "Start chatting"
                    size_hint: .66, .065
                    pos_hint: {"center_x": .5, "center_y": .65}
                    background_color: 0, 0, 0, 0
                    front_name: "BPoppins"
                    on_release:
                        root.manager.transition.direction = "left"
                        root.manager.current = "chat_private"
                    canvas.before:
                        Color:
                            rgb: rgba(52, 0, 231, 255)
                        RoundedRectangle:
                            size: self.size
                            pos: self.pos
                            radius: [5]
                Button:
                    text: "Groups"
                    size_hint: .66, .065
                    pos_hint: {"center_x": .5, "center_y": .55}
                    background_color: 0, 0, 0, 0
                    front_name: "BPoppins"
                    color: rgba(52, 0, 231, 255)
                    on_release:
                        root.manager.transition.direction = "left"
                        root.manager.current = "group"
                    canvas.before:
                        Color:
                            rgb: rgba(52, 0, 231, 255)
                        Line:
                            width: 1.2
                            rounded_rectangle: self.x, self.y, self.width, self.height, 5, 5, 5, 5, 100
                Button:
                    text: "Settings"
                    size_hint: .66, .065
                    pos_hint: {"center_x": .5, "center_y": .45}
                    background_color: 0, 0, 0, 0
                    front_name: "BPoppins"
                    color: rgba(52, 0, 231, 255)
                    on_release:
                        root.manager.transition.direction = "left"
                        root.manager.current = "settings"
                    canvas.before:
                        Color:
                            rgb: rgba(52, 0, 231, 255)
                        Line:
                            width: 1.2
                            rounded_rectangle: self.x, self.y, self.width, self.height, 5, 5, 5, 5, 100
                Button:
                    text: "Personal"
                    size_hint: .66, .065
                    pos_hint: {"center_x": .5, "center_y": .35}
                    background_color: 0, 0, 0, 0
                    front_name: "BPoppins"
                    color: rgba(52, 0, 231, 255)
                    on_release:
                        root.manager.transition.direction = "left"
                        root.manager.current = "personal"
                    canvas.before:
                        Color:
                            rgb: rgba(52, 0, 231, 255)
                        Line:
                            width: 1.2
                            rounded_rectangle: self.x, self.y, self.width, self.height, 5, 5, 5, 5, 100
                Button:
                    text: "My ID"
                    size_hint: .66, .065
                    pos_hint: {"center_x": .5, "center_y": .15}
                    background_color: 0, 0, 0, 0
                    front_name: "BPoppins"
                    color: rgba(52, 0, 231, 255)
                    on_release:
                        app.show_id()
                    canvas.before:
                        Color:
                            rgb: rgba(52, 0, 231, 255)
                        Line:
                            width: 1.2
                            rounded_rectangle: self.x, self.y, self.width, self.height, 5, 5, 5, 5, 100

                MDIconButton:
                    icon: "logout"
                    pos_hint: {"center_x": .9, "center_y": .05}
                    on_release:
                        root.manager.transition.direction = "left"
                        root.manager.current = "main"


            MDBottomNavigationItem:
                name: "test"
                text: "Chats"
                icon: "chat"

                MDIconButton:
                    icon: "arrow-left"
                    pos_hint: {"center_y": .95}
                    user_font_size: "30sp"
                    theme_text_color: "Custom"
                    text_color: rgba(26, 24, 58, 255)
                    on_release:
                        root.manager.transition.direction = "right"
                        root.manager.current = "home"

                MDLabel:
                    text: "Chats"
                    font_name: "BPoppins"
                    font_size: "23sp"
                    pos_hint: {"center_y": .8}
                    halign: "center"
                    color: rgba(34, 34, 34, 255)
                Button:
                    text: "Start chatting"
                    size_hint: .66, .065
                    pos_hint: {"center_x": .5, "center_y": .65}
                    background_color: 0, 0, 0, 0
                    front_name: "BPoppins"
                    on_release:
                        root.manager.transition.direction = "left"
                        root.manager.current = "chat_private"
                    canvas.before:
                        Color:
                            rgb: rgba(52, 0, 231, 255)
                        RoundedRectangle:
                            size: self.size
                            pos: self.pos
                            radius: [5]
                Button:
                    text: "Load chats"
                    size_hint: .66, .065
                    pos_hint: {"center_x": .5, "center_y": .55}
                    background_color: 0, 0, 0, 0
                    front_name: "BPoppins"
                    color: rgba(52, 0, 231, 255)
                    on_release:
                        root.manager.transition.direction = "left"
                        root.manager.current = "chat_load"
                    canvas.before:
                        Color:
                            rgb: rgba(52, 0, 231, 255)
                        Line:
                            width: 1.2
                            rounded_rectangle: self.x, self.y, self.width, self.height, 5, 5, 5, 5, 100

            MDBottomNavigationItem:
                name: "test2"
                text: "Settings"
                icon: "account-settings"

                MDIconButton:
                    icon: "arrow-left"
                    pos_hint: {"center_y": .95}
                    user_font_size: "30sp"
                    theme_text_color: "Custom"
                    text_color: rgba(26, 24, 58, 255)
                    on_release:
                        root.manager.transition.direction = "right"
                        root.manager.current = "main"

                MDLabel:
                    text: "Settings"
                    font_name: "BPoppins"
                    font_size: "26sp"
                    pos_hint: {"center_x": .6, "center_y": .85}
                    color: rgba(0, 0, 59, 255)

                MDFloatLayout:
                    size_hint_y: .11
                    MDFloatLayout:
                        size_hint: .8, .75
                        pos_hint: {"center_x": .43, "center_y": 7}
                        TextInput:
                            id: text_input2
                            hint_text: "Set a new username"
                            size_hint: 1, None
                            pos_hint: {"center_x": .5, "center_y": .5}
                            font_size: "12sp"
                            height: self.minimum_height
                            multiline: False
                            cursor_color: 1, 170/255, 23/255, 1
                            cursor_width: "2sp"
                            background_color: 0, 0, 0, 0
                            padding: 15
                            font_name: "BPoppins"
                    MDIconButton:
                        id: username_icon
                        icon: "account-cog"
                        pos_hint: {"center_x": .91, "center_y": 7}
                        user_font_size: "12sp"
                        text_color: 1, 1, 1, 1
                        on_release:
                            app.change_username(text_input2.text)

                MDFloatLayout:
                    size_hint_y: .11
                    MDFloatLayout:
                        size_hint: .8, .75
                        pos_hint: {"center_x": .43, "center_y": 6}
                        TextInput:
                            id: text_input3
                            hint_text: "Set a new password"
                            size_hint: 1, None
                            pos_hint: {"center_x": .5, "center_y": .5}
                            font_size: "12sp"
                            height: self.minimum_height
                            multiline: False
                            cursor_color: 1, 170/255, 23/255, 1
                            cursor_width: "2sp"
                            background_color: 0, 0, 0, 0
                            padding: 15
                            font_name: "BPoppins"
                    MDIconButton:
                        id: password_icon
                        icon: "account-cog"
                        pos_hint: {"center_x": .91, "center_y": 6}
                        user_font_size: "12sp"
                        text_color: 1, 1, 1, 1
                        on_release:
                            app.change_password(text_input3.text)
                Button:
                    text: "Delete Everything"
                    size_hint: .66, .065
                    pos_hint: {"center_x": .5, "center_y": .35}
                    background_color: 0, 0, 0, 0
                    front_name: "BPoppins"
                    color: rgba(52, 0, 231, 255)
                    on_release:
                        app.delete_everything()
                    canvas.before:
                        Color:
                            rgb: rgba(52, 0, 231, 255)
                        Line:
                            width: 1.2
                            rounded_rectangle: self.x, self.y, self.width, self.height, 5, 5, 5, 5, 100


            MDBottomNavigationItem:
                name: "test3"
                text: "Help"
                icon: "help-circle"

                MDLabel:
                    text: "Help"
                    font_name: "BPoppins"
                    font_size: "26sp"
                    pos_hint: {"center_x": .6, "center_y": .85}
                    color: rgba(0, 0, 59, 255)

                MDLabel:
                    text: "Found a bug or improvements?"
                    font_name: "BPoppins"
                    font_size: "11sp"
                    pos_hint: {"center_x": .68, "center_y": .75}
                    color: rgba(0, 0, 59, 255)
                MDTextButton:
                    text: "Contact Us"
                    font_name: "BPoppins"
                    font_size: "11sp"
                    pos_hint: {"center_x": .68, "center_y": .7}
                    color: rgba(135, 133, 193, 255)
                    on_release:
                        webbrowser.open("https://protdos.com/contact.html")

                MDLabel:
                    text: "Contact us"
                    font_name: "BPoppins"
                    font_size: "11sp"
                    pos_hint: {"center_x": .68, "center_y": .55}
                    color: rgba(0, 0, 59, 255)
                MDTextButton:
                    text: "Mail Us"
                    font_name: "BPoppins"
                    font_size: "11sp"
                    pos_hint: {"center_x": .68, "center_y": .5}
                    color: rgba(135, 133, 193, 255)
                    on_release:
                        webbrowser.open("mailto:rootcode@duck.com")


