MDScreen:
    name: "bad"
    MDFloatLayout:
        md_bg_color: 1, 1, 1, 1
        MDIconButton:
            icon: "arrow-left"
            pos_hint: {"center_y": .95}
            user_font_size: "30sp"
            theme_text_color: "Custom"
            text_color: rgba(26, 24, 58, 255)
            on_release:
                root.manager.transition.direction = "left"
                root.manager.current = "main"
        MDLabel:
            text: "Ooops..."
            font_name: "BPoppins"
            font_size: "23sp"
            pos_hint: {"center_y": .8}
            halign: "center"
            color: rgba(34, 34, 34, 255)
        MDLabel:
            text: "The credentials you entered are not valid."
            font_name: "BPoppins"
            font_size: "13sp"
            size_hint_x: .85
            pos_hint: {"center_x": .5, "center_y": .7}
            halign: "center"
            color: rgba(127, 127, 127, 255)
        Button:
            text: "Go back."
            size_hint: .66, .065
            pos_hint: {"center_x": .5, "center_y": .3}
            background_color: 0, 0, 0, 0
            front_name: "BPoppins"
            on_release:
                root.manager.transition.direction = "left"
                root.manager.current = "login"
            canvas.before:
                Color:
                    rgb: rgba(52, 0, 231, 255)
                RoundedRectangle:
                    size: self.size
                    pos: self.pos
                    radius: [5]

